version: 0.0
os: linux
files:
  - source : /
    destination: /home/ubuntu/prime
permissions:
  - object: /home/ec2-user/prime
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user
